### ISSUE TITLE
Change name of host in local set

### ISSUE THREAD

**Issue by likeuntomurphy** [fostermadeco/rokanan#8]
Instead of

```
all:
  hosts:
    local:
      ansible_host: 192.168.203.101
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
```

use 

```
all:
  children:
    local:
      hosts:
        vagrant:
          ansible_host: hostname.test
```

and change the ansible limit in Vagrantfile from `local` to `vagrant`.

This is for better compatibility when a remote group exists and to suppress the duplicate group/host name warning that is issued when using `all.children.local.hosts.local = hostname.test`.
